# Filename: .travis.yml

language: python
cache: pip
# https://github.com/travis-ci/travis-ci/issues/9815
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
      - python: 3.7
        dist: xenial
        sudo: true
install:
- pip install --upgrade -r requirements.txt
- pip install --upgrade -r requirements-dev.txt
#script:
#- pylint booklib
#- pip install -e . && python -m pytest tests

notifications:
  slack: curious-minds-101:Wkf5gPKQyJalUZ99Oyql0Zav