LABELS = {
    'en': {
        'AdminWindow': {
            'title': 'Admin Panel',
            'account_btn': 'Account',
            'book_btn': 'Book',
            'search_btn': 'Search',
        },
        'AccountWindow': {
            'title': 'Account',
            'new_account_form': 'New Account',
            'first_name_txt': 'First Name',
            'family_name_txt': 'Family Name',
            'dob_txt': 'Date of birth',
            'gov_id_txt': 'Government ID',
            'phone_number_txt': 'Phone #',
            'school_txt': 'School Name',
            'class_level_txt': 'Class/Level',
            'ok_btn': 'OK',
            'clear_btn': 'Clear',
            'cancel_btn': 'Cancel',
            'errors': {
                'no_first_name': 'First name cannot be empty',
                'no_last_name': 'Family name cannot be empty',
                'no_phone_number': 'Phone number cannot be empty',
                'no_gov_id': 'Age is greater than or equal to {}, '
                               'government ID is required',
            },
        },
        'BookWindow': {
            'title': 'Book',
            'isbn_no_txt': 'ISBN Number',
            'call_no_txt': 'Call Number',
            'category_txt': 'Categories',
            'categories_checkboxes': {
                'children': 'Children',
                'adult': 'Adult',
                'young_adult': 'Young Adult',
                'teen': 'Teen',
                'animals': 'Animals',
                'nature': 'Nature',
                'religious': 'Religious',
                'comic': 'Comic',
                'others': 'Others',
            },
            'level_txt': 'Level',
            'reading_levels': {
                'early_reader': 'Early Reader',
                'one_to_three': 'One to Three',
                'four_to_six': 'Four to Six',
                'middle_school': 'Middle School',
                'high_school': 'High School',
                'advanced': 'Advanced',
                'others': 'Others',
            },
            'title_txt': 'Title',
            'authors_txt': 'Authors',
            'publisher_txt': 'Publisher',
            'ok_btn': 'OK',
            'cancel_btn': 'Cancel',
            'errors': {
                'no_isbn': 'ISBN number cannot be empty',
                'invalid_isbn': 'ISBN number field contains non-numeric value',
            },
        },
    },
    'fr': {
        'AdminWindow': {
            'title': 'panneau administrateur',
            'account_btn': 'ajouter un compte',
            'book_btn': 'Book',
            'search_btn': 'Search',
        },
        'AccountWindow': {
            'title': 'Account',
            'new_account_form': 'New Account',
            'first_name_txt': 'First Name',
            'family_name_txt': 'Family Name',
            'dob_txt': 'Date of birth',
            'gov_id_txt': 'Government ID',
            'phone_number_txt': 'Phone #',
            'school_txt': 'School Name',
            'class_level_txt': 'Class/Level',
            'ok_btn': 'OK',
            'clear_btn': 'Clear',
            'cancel_btn': 'Cancel',
            'errors': {
                'no_first_name': 'First name cannot be empty',
                'no_last_name': 'Family name cannot be empty',
                'no_phone_number': 'Phone number cannot be empty',
                'no_gov_id': 'Age is greater than or equal to {}, '
                               'government ID is required',
            },
        },
        'BookWindow': {
            'title': 'Book',
            'isbn_no_txt': 'ISBN Number',
            'call_no_txt': 'Call Number',
            'category_txt': 'Categories',
            'categories_checkboxes': {
                'children': 'Children',
                'adult': 'Adult',
                'young_adult': 'Young Adult',
                'teen': 'Teen',
                'animals': 'Animals',
                'nature': 'Nature',
                'religious': 'Religious',
                'comic': 'Comic',
                'others': 'Others',
            },
            'level_txt': 'Level',
            'reading_levels': {
                'early_reader': 'Early Reader',
                'one_to_three': 'One to Three',
                'four_to_six': 'Four to Six',
                'middle_school': 'Middle School',
                'high_school': 'High School',
                'advanced': 'Advanced',
                'others': 'Others',
            },
            'title_txt': 'Title',
            'authors_txt': 'Authors',
            'publisher_txt': 'Publisher',
            'ok_btn': 'OK',
            'cancel_btn': 'Cancel',
            'errors': {
                'no_isbn': 'ISBN number cannot be empty',
                'invalid_isbn': 'ISBN number field contains non-numeric value',
            },
        },
    },
}

